"""add phone number to users table

Revision ID: 791b4be65a8f
Revises: aa590aacf397
Create Date: 2023-05-30 14:59:31.743906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791b4be65a8f'
down_revision = 'aa590aacf397'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
